# Generated by Django 3.0.8 on 2020-07-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200708_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
